//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squash.Web.Resources.Shared
{
    using System.Globalization;
    using System.Resources;

    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXFileCodeGenerator", "4.0.0.0")]
    [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
    public class Validation
    {
        private static ResourceManager? resourceMan;
        private static CultureInfo? resourceCulture;

        public Validation()
        {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static ResourceManager ResourceManager
        {
            get
            {
                resourceMan ??= new ResourceManager("Squash.Web.Resources.Shared.Validation", typeof(Validation).Assembly);
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static CultureInfo? Culture
        {
            get => resourceCulture;
            set => resourceCulture = value;
        }

        public static string Required => ResourceManager.GetString("Required", resourceCulture) ?? string.Empty;

        public static string InvalidEmail => ResourceManager.GetString("InvalidEmail", resourceCulture) ?? string.Empty;

        public static string SelectOption => ResourceManager.GetString("SelectOption", resourceCulture) ?? string.Empty;

        public static string PasswordMismatch => ResourceManager.GetString("PasswordMismatch", resourceCulture) ?? string.Empty;

        public static string InvalidCode => ResourceManager.GetString("InvalidCode", resourceCulture) ?? string.Empty;

        public static string EmailNotConfirmed => ResourceManager.GetString("EmailNotConfirmed", resourceCulture) ?? string.Empty;

        public static string ConfirmationEmailSent => ResourceManager.GetString("ConfirmationEmailSent", resourceCulture) ?? string.Empty;

        public static string RateLimitExceeded => ResourceManager.GetString("RateLimitExceeded", resourceCulture) ?? string.Empty;
    }
}
