// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Squash.SqlServer;

#nullable disable

namespace Squash.SqlServer.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260117235618_InitialData")]
    partial class InitialData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Squash.DataAccess.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CountryName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Nationality")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CZE",
                            CountryName = "Чехия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Чехия"
                        },
                        new
                        {
                            Id = 2,
                            Code = "POR",
                            CountryName = "Португалия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Португалия"
                        },
                        new
                        {
                            Id = 3,
                            Code = "POL",
                            CountryName = "Полша",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Полша"
                        },
                        new
                        {
                            Id = 4,
                            Code = "DEN",
                            CountryName = "Дания",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Дания"
                        },
                        new
                        {
                            Id = 5,
                            Code = "SUI",
                            CountryName = "Швейцария",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Швейцария"
                        },
                        new
                        {
                            Id = 6,
                            Code = "BEL",
                            CountryName = "Белгия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Белгия"
                        },
                        new
                        {
                            Id = 7,
                            Code = "IRL",
                            CountryName = "Ирландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Ирландия"
                        },
                        new
                        {
                            Id = 8,
                            Code = "ENG",
                            CountryName = "Англия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Англия"
                        },
                        new
                        {
                            Id = 9,
                            Code = "ISR",
                            CountryName = "Израел",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Израел"
                        },
                        new
                        {
                            Id = 10,
                            Code = "ESP",
                            CountryName = "Испания",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Испания"
                        },
                        new
                        {
                            Id = 11,
                            Code = "AUT",
                            CountryName = "Австрия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Австрия"
                        },
                        new
                        {
                            Id = 12,
                            Code = "CRO",
                            CountryName = "Хърватия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Хърватия"
                        },
                        new
                        {
                            Id = 13,
                            Code = "HUN",
                            CountryName = "Унгария",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Унгария"
                        },
                        new
                        {
                            Id = 14,
                            Code = "GER",
                            CountryName = "Германия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Германия"
                        },
                        new
                        {
                            Id = 15,
                            Code = "SVK",
                            CountryName = "Словакия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Словакия"
                        },
                        new
                        {
                            Id = 16,
                            Code = "ROM",
                            CountryName = "Румъния",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Румъния"
                        },
                        new
                        {
                            Id = 17,
                            Code = "NED",
                            CountryName = "Нидерландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Нидерландия"
                        },
                        new
                        {
                            Id = 18,
                            Code = "UKR",
                            CountryName = "Украйна",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Украйна"
                        },
                        new
                        {
                            Id = 19,
                            Code = "KSA",
                            CountryName = "Саудитска Арабия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Саудитска Арабия"
                        },
                        new
                        {
                            Id = 20,
                            Code = "NIR",
                            CountryName = "Северна Ирландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Северна Ирландия"
                        },
                        new
                        {
                            Id = 21,
                            Code = "ITA",
                            CountryName = "Италия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Италия"
                        },
                        new
                        {
                            Id = 22,
                            Code = "JPN",
                            CountryName = "Япония",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Япония"
                        },
                        new
                        {
                            Id = 23,
                            Code = "FRA",
                            CountryName = "Франция",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Франция"
                        },
                        new
                        {
                            Id = 24,
                            Code = "MON",
                            CountryName = "Монако",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Монако"
                        },
                        new
                        {
                            Id = 25,
                            Code = "BRA",
                            CountryName = "Бразилия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Бразилия"
                        },
                        new
                        {
                            Id = 26,
                            Code = "WAL",
                            CountryName = "Уелс",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Уелс"
                        },
                        new
                        {
                            Id = 27,
                            Code = "MRI",
                            CountryName = "Мавриций",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Мавриций"
                        },
                        new
                        {
                            Id = 28,
                            Code = "BUL",
                            CountryName = "България",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "България"
                        },
                        new
                        {
                            Id = 29,
                            Code = "EST",
                            CountryName = "Естония",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Естония"
                        },
                        new
                        {
                            Id = 30,
                            Code = "EGY",
                            CountryName = "Египет",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Египет"
                        },
                        new
                        {
                            Id = 31,
                            Code = "NOR",
                            CountryName = "Норвегия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Норвегия"
                        },
                        new
                        {
                            Id = 32,
                            Code = "MEX",
                            CountryName = "Мексико",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Мексико"
                        },
                        new
                        {
                            Id = 33,
                            Code = "PAK",
                            CountryName = "Пакистан",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Пакистан"
                        },
                        new
                        {
                            Id = 34,
                            Code = "CHN",
                            CountryName = "Китай",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Китай"
                        },
                        new
                        {
                            Id = 35,
                            Code = "MAC",
                            CountryName = "Макао",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Макао"
                        },
                        new
                        {
                            Id = 36,
                            Code = "LUX",
                            CountryName = "Люксембург",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Люксембург"
                        },
                        new
                        {
                            Id = 37,
                            Code = "GRE",
                            CountryName = "Гърция",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Гърция"
                        },
                        new
                        {
                            Id = 38,
                            Code = "IND",
                            CountryName = "Индия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Индия"
                        },
                        new
                        {
                            Id = 39,
                            Code = "RSF",
                            CountryName = "Русия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Русия"
                        },
                        new
                        {
                            Id = 40,
                            Code = "SCO",
                            CountryName = "Шотландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Шотландия"
                        },
                        new
                        {
                            Id = 41,
                            Code = "PNG",
                            CountryName = "Папуа Нова Гвинея",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Папуа Нова Гвинея"
                        },
                        new
                        {
                            Id = 42,
                            Code = "USA",
                            CountryName = "САЩ",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "САЩ"
                        },
                        new
                        {
                            Id = 43,
                            Code = "MLT",
                            CountryName = "Малта",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Малта"
                        },
                        new
                        {
                            Id = 44,
                            Code = "PYF",
                            CountryName = "Френска Полинезия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Френска Полинезия"
                        },
                        new
                        {
                            Id = 45,
                            Code = "TUR",
                            CountryName = "Турция",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Турция"
                        },
                        new
                        {
                            Id = 46,
                            Code = "FIN",
                            CountryName = "Финландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Финландия"
                        },
                        new
                        {
                            Id = 47,
                            Code = "QAT",
                            CountryName = "Катар",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Катар"
                        },
                        new
                        {
                            Id = 48,
                            Code = "SWE",
                            CountryName = "Швеция",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Швеция"
                        },
                        new
                        {
                            Id = 49,
                            Code = "MAS",
                            CountryName = "Малайзия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Малайзия"
                        },
                        new
                        {
                            Id = 50,
                            Code = "KUW",
                            CountryName = "Кувейт",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Кувейт"
                        },
                        new
                        {
                            Id = 51,
                            Code = "CAN",
                            CountryName = "Канада",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Канада"
                        },
                        new
                        {
                            Id = 52,
                            Code = "THA",
                            CountryName = "Тайланд",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Тайланд"
                        },
                        new
                        {
                            Id = 53,
                            Code = "GUY",
                            CountryName = "Гаяна",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Гаяна"
                        },
                        new
                        {
                            Id = 54,
                            Code = "AUS",
                            CountryName = "Австралия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Австралия"
                        },
                        new
                        {
                            Id = 55,
                            Code = "ZIM",
                            CountryName = "Зимбабве",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Зимбабве"
                        },
                        new
                        {
                            Id = 56,
                            Code = "HKG",
                            CountryName = "Хонконг",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Хонконг"
                        },
                        new
                        {
                            Id = 57,
                            Code = "SIN",
                            CountryName = "Сингапур",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Сингапур"
                        },
                        new
                        {
                            Id = 58,
                            Code = "KOR",
                            CountryName = "Южна Корея",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Южна Корея"
                        },
                        new
                        {
                            Id = 59,
                            Code = "GGY",
                            CountryName = "Гърнси",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Гърнси"
                        },
                        new
                        {
                            Id = 60,
                            Code = "PER",
                            CountryName = "Перу",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Перу"
                        },
                        new
                        {
                            Id = 61,
                            Code = "IVB",
                            CountryName = "Британски Вирджински острови",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Британски Вирджински острови"
                        },
                        new
                        {
                            Id = 62,
                            Code = "RSA",
                            CountryName = "Южна Африка",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Южна Африка"
                        },
                        new
                        {
                            Id = 63,
                            Code = "TPE",
                            CountryName = "Китайски Тайпей",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Китайски Тайпей"
                        },
                        new
                        {
                            Id = 64,
                            Code = "MAR",
                            CountryName = "Мароко",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Мароко"
                        },
                        new
                        {
                            Id = 65,
                            Code = "ARG",
                            CountryName = "Аржентина",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Аржентина"
                        },
                        new
                        {
                            Id = 66,
                            Code = "NZL",
                            CountryName = "Нова Зеландия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Нова Зеландия"
                        },
                        new
                        {
                            Id = 67,
                            Code = "GBR",
                            CountryName = "Великобритания",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Великобритания"
                        },
                        new
                        {
                            Id = 68,
                            Code = "COL",
                            CountryName = "Колумбия",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Колумбия"
                        },
                        new
                        {
                            Id = 69,
                            Code = "KEN",
                            CountryName = "Кения",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Кения"
                        },
                        new
                        {
                            Id = 70,
                            Code = "SRI",
                            CountryName = "Шри Ланка",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Шри Ланка"
                        },
                        new
                        {
                            Id = 71,
                            Code = "UAE",
                            CountryName = "Обединени арабски емирства",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastOperationUserId = 0,
                            Nationality = "Обединени арабски емирства"
                        });
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Court", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VenueId");

                    b.ToTable("Courts");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Draw", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("EventId")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalDrawId")
                        .HasColumnType("int");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TournamentId");

                    b.ToTable("Draws");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Direction")
                        .HasColumnType("int");

                    b.Property<int?>("ExternalEventId")
                        .HasColumnType("int");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("MatchType")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.GameLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("MatchGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchGameId");

                    b.ToTable("GameLogs");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Language", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Languages");

                    b.HasData(
                        new
                        {
                            Code = "bg-BG",
                            Name = "Български"
                        },
                        new
                        {
                            Code = "en-GB",
                            Name = "English"
                        });
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DrawId")
                        .HasColumnType("int");

                    b.Property<string>("HeadToHeadUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("PinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Player1Id")
                        .HasColumnType("int");

                    b.Property<bool>("Player1Walkover")
                        .HasColumnType("bit");

                    b.Property<int?>("Player2Id")
                        .HasColumnType("int");

                    b.Property<bool>("Player2Walkover")
                        .HasColumnType("bit");

                    b.Property<int?>("RoundId")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("StartTimeText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TournamentDayId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("DrawId");

                    b.HasIndex("Player1Id");

                    b.HasIndex("Player2Id");

                    b.HasIndex("RoundId");

                    b.HasIndex("TournamentDayId");

                    b.HasIndex("TournamentId");

                    b.HasIndex("WinnerPlayerId");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.MatchGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("GameNumber")
                        .HasColumnType("int");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<int?>("Side1Points")
                        .HasColumnType("int");

                    b.Property<int?>("Side2Points")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerSide")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.ToTable("MatchGames");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.MatchGameEventLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("Event")
                        .HasColumnType("int");

                    b.Property<bool>("IsPoint")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<int>("MatchGameId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchGameId");

                    b.ToTable("MatchGameEventLogs");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntitySourceId")
                        .HasColumnType("int");

                    b.Property<string>("EsfMemberId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImaId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PictureUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RankedinId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("DrawId")
                        .HasColumnType("int");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DrawId");

                    b.ToTable("Rounds");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.SitemapEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeFrequency")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Culture")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<decimal?>("Priority")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Culture");

                    b.HasIndex("IsEnabled");

                    b.ToTable("SitemapEntries");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Tournament", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ClosingSigninDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntitySourceId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EntryOpensDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ExternalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrganizationCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Regulations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Slug")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SourceUrls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("WithdrawalDeadlineDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("IsPublished");

                    b.HasIndex("Slug");

                    b.HasIndex("UserId");

                    b.ToTable("Tournaments");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentCourt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CourtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CourtId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentCourts");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("LocationFilter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentDays");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int?>("TournamentPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TournamentId");

                    b.ToTable("TournamentPlayers");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentVenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<int>("TournamentId")
                        .HasColumnType("int");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TournamentId");

                    b.HasIndex("VenueId");

                    b.ToTable("TournamentVenues");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("BadgeId")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailNotificationsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("IdentityUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("PlayerId")
                        .HasColumnType("int");

                    b.Property<string>("PreferredLanguage")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("PreferredSport")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("VerificationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Verified")
                        .HasColumnType("bit");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdentityUserId")
                        .IsUnique();

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasFilter("[PlayerId] IS NOT NULL");

                    b.HasIndex("PreferredLanguage");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "System",
                            BirthDate = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            City = "System",
                            DateCreated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateUpdated = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "system@squash.local",
                            EmailNotificationsEnabled = false,
                            Gender = "Unknown",
                            IdentityUserId = "SYSTEM",
                            LastOperationUserId = 0,
                            Name = "System",
                            Phone = "N/A",
                            PreferredLanguage = "bg-BG",
                            Verified = true,
                            Zip = "0000"
                        });
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Venue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("LastOperationUserId")
                        .HasColumnType("int");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Region")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Zip")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Venues");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Court", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Venue", "Venue")
                        .WithMany("Courts")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Draw", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId");

                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("Draws")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Event", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("Events")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.GameLog", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.MatchGame", "MatchGame")
                        .WithMany()
                        .HasForeignKey("MatchGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchGame");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Match", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Court", "Court")
                        .WithMany("Matches")
                        .HasForeignKey("CourtId");

                    b.HasOne("Squash.DataAccess.Entities.Draw", "Draw")
                        .WithMany("Matches")
                        .HasForeignKey("DrawId");

                    b.HasOne("Squash.DataAccess.Entities.Player", "Player1")
                        .WithMany()
                        .HasForeignKey("Player1Id");

                    b.HasOne("Squash.DataAccess.Entities.Player", "Player2")
                        .WithMany()
                        .HasForeignKey("Player2Id");

                    b.HasOne("Squash.DataAccess.Entities.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId");

                    b.HasOne("Squash.DataAccess.Entities.TournamentDay", "TournamentDay")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentDayId");

                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("Matches")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squash.DataAccess.Entities.Player", "WinnerPlayer")
                        .WithMany()
                        .HasForeignKey("WinnerPlayerId");

                    b.Navigation("Court");

                    b.Navigation("Draw");

                    b.Navigation("Player1");

                    b.Navigation("Player2");

                    b.Navigation("Round");

                    b.Navigation("Tournament");

                    b.Navigation("TournamentDay");

                    b.Navigation("WinnerPlayer");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.MatchGame", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Match", "Match")
                        .WithMany("Games")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Match");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.MatchGameEventLog", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.MatchGame", "MatchGame")
                        .WithMany("EventLogs")
                        .HasForeignKey("MatchGameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MatchGame");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Player", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Country", "Country")
                        .WithMany("Players")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Round", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Draw", "Draw")
                        .WithMany("Rounds")
                        .HasForeignKey("DrawId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Draw");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Tournament", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squash.DataAccess.Entities.User", "User")
                        .WithMany("Tournaments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentCourt", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Court", "Court")
                        .WithMany("TournamentCourts")
                        .HasForeignKey("CourtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("TournamentCourts")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Court");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentDay", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("Days")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentPlayer", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Player", "Player")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("TournamentPlayers")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Tournament");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentVenue", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Tournament", "Tournament")
                        .WithMany("TournamentVenues")
                        .HasForeignKey("TournamentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Squash.DataAccess.Entities.Venue", "Venue")
                        .WithMany("TournamentVenues")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tournament");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.User", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId");

                    b.HasOne("Squash.DataAccess.Entities.Player", "Player")
                        .WithOne("User")
                        .HasForeignKey("Squash.DataAccess.Entities.User", "PlayerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Squash.DataAccess.Entities.Language", "Language")
                        .WithMany()
                        .HasForeignKey("PreferredLanguage")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Country");

                    b.Navigation("Language");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Venue", b =>
                {
                    b.HasOne("Squash.DataAccess.Entities.Country", "Country")
                        .WithMany("Venues")
                        .HasForeignKey("CountryId");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Country", b =>
                {
                    b.Navigation("Players");

                    b.Navigation("Venues");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Court", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("TournamentCourts");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Draw", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Match", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.MatchGame", b =>
                {
                    b.Navigation("EventLogs");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Player", b =>
                {
                    b.Navigation("TournamentPlayers");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Tournament", b =>
                {
                    b.Navigation("Days");

                    b.Navigation("Draws");

                    b.Navigation("Events");

                    b.Navigation("Matches");

                    b.Navigation("TournamentCourts");

                    b.Navigation("TournamentPlayers");

                    b.Navigation("TournamentVenues");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.TournamentDay", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.User", b =>
                {
                    b.Navigation("Tournaments");
                });

            modelBuilder.Entity("Squash.DataAccess.Entities.Venue", b =>
                {
                    b.Navigation("Courts");

                    b.Navigation("TournamentVenues");
                });
#pragma warning restore 612, 618
        }
    }
}
